// Code generated by "stringer -type=isKind -linecomment"; DO NOT EDIT.

package serializer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[isSlice-1]
	_ = x[isByteSlice-2]
	_ = x[isArray-3]
	_ = x[isByteArray-4]
	_ = x[isStruct-5]
	_ = x[isAnonStruct-6]
	_ = x[isMap-7]
	_ = x[isMapStruct-8]
	_ = x[isPointer-9]
}

const _isKind_name = "SliceBytesArrayByteArrayStructAnonStructMapMapStructPointer"

var _isKind_index = [...]uint8{0, 5, 10, 15, 24, 30, 40, 43, 52, 59}

func (i isKind) String() string {
	i -= 1
	if i >= isKind(len(_isKind_index)-1) {
		return "isKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _isKind_name[_isKind_index[i]:_isKind_index[i+1]]
}
